import { mkdir, writeFile, readdir, readFile } from 'fs/promises';
import path from 'path';
import os from 'os';
import { nanoid } from 'nanoid';
import type { Session, SessionState } from '../types.js';

const log = (msg: string) => process.stderr.write(`[serge] ${msg}\n`);

const SERGE_DIR = path.join(os.homedir(), '.serge');
const SESSIONS_DIR = path.join(SERGE_DIR, 'sessions');
const REPORTS_DIR = path.join(SERGE_DIR, 'reports');

export function getSergeDir() { return SERGE_DIR; }
export function getSessionsDir() { return SESSIONS_DIR; }
export function getReportsDir() { return REPORTS_DIR; }

export async function startSession(domain: string, task: string): Promise<SessionState> {
  const date = new Date().toISOString().split('T')[0];
  const domainSlug = domain.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const sessionId = `${date}-${domainSlug}-${nanoid(12)}`;

  const sessionDir = path.join(SESSIONS_DIR, sessionId);
  const screenshotsDir = path.join(sessionDir, 'screenshots');

  await mkdir(screenshotsDir, { recursive: true });
  await mkdir(REPORTS_DIR, { recursive: true });

  const session: Session = {
    session_id: sessionId,
    domain,
    task,
    started_at: new Date().toISOString(),
    total_steps: 0,
    total_duration_ms: 0,
    actions: [],
    network: [],
  };

  log(`Session started: ${sessionId}`);

  return {
    session,
    current_step: 0,
    session_dir: sessionDir,
    screenshots_dir: screenshotsDir,
    start_time: performance.now(),
  };
}

export async function endSession(
  state: SessionState,
  outcome: 'success' | 'failure' | 'partial',
  notes: string
): Promise<{ session_id: string; report_path: string; summary: Session }> {
  const totalDuration = Math.round(performance.now() - state.start_time);

  state.session.ended_at = new Date().toISOString();
  state.session.outcome = outcome;
  state.session.notes = notes;
  state.session.total_steps = state.current_step;
  state.session.total_duration_ms = totalDuration;

  // Save session JSON
  const sessionPath = path.join(state.session_dir, 'session.json');
  await writeFile(sessionPath, JSON.stringify(state.session, null, 2));
  log(`Session saved: ${sessionPath}`);

  // Report path (will be generated by report module)
  const reportPath = path.join(REPORTS_DIR, `${state.session.session_id}.html`);

  return {
    session_id: state.session.session_id,
    report_path: reportPath,
    summary: state.session,
  };
}

export async function listSessions(): Promise<Session[]> {
  try {
    const entries = await readdir(SESSIONS_DIR);
    const sessions: Session[] = [];

    for (const entry of entries.sort().reverse()) {
      const sessionPath = path.join(SESSIONS_DIR, entry, 'session.json');
      try {
        const data = await readFile(sessionPath, 'utf-8');
        sessions.push(JSON.parse(data));
      } catch {
        // Skip invalid sessions
      }
    }

    return sessions;
  } catch {
    return [];
  }
}

export async function getLatestSession(): Promise<Session | null> {
  const sessions = await listSessions();
  return sessions[0] ?? null;
}
